### ISSUE TITLE
We need to test that we can handle multiple sessions and multiple streams per session at the native level

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#1051]
In reviewing the iOS code I didn't see any tests that really stressed the browser or advertiser. That is, had them deal with multiple simultaneous MCSessions. I also didn't see tests that showed us handling multiple virtual sockets in a single MCSession. Do we just want to rely on the Node level tests for this or should we have some iOS tests? I'm mostly worried because the Node tests will only test via the whole TCP layer which will make it harder to find issues. It seems like we should have native tests down at the MCSession layer to make sure everything there is solid. @baydet and @dersim-davaod what do you think?

**Comment by baydet** [comment]
I think the best solution in our case will be creation of coordinated native tests as you've talked earlier. Because we definetely cannot rely on performance of one device transmitting data to itself. And for bluetooth for example we cannot make these tests with one device at all. And yes, we haven't to use the whole Thali stack. This could bring us to situation when we have ONE BIG FAILING TEST. What reminds me about how @evabishchevich suffered(/ing?).

**Comment by yaronyg** [comment]
This test is in the PR but it isn't passing so we are going to keep this bug around until it passes.

**Comment by dersim-davaod** [comment]
Still working. Looks like there are 4 places with issues in the code. I've fixed 2 of them.

**Comment by dersim-davaod** [comment]
Continue working.
Looks like there are 4 places with issues in the code. I've fixed 2 of them. And these fixes will be in #1199.
