### ISSUE TITLE
Session.swift - Should createOutputStream enqueue requests if the session isn't connected?

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#1052]
In createOutputStream if we get a call when the session isn't in .Connected then we append the request. But as I argue below we shouldn't be able to get such a request.

Time 0 - B starts to browse and discovers A
Time 1 - B notifies its node code that it has discovered A
Time 2 - The node code on B calls multiConnect(A)
Time 3 - B sends an MCSession invite to A to join MCSession BA
Time 4 - A receives the MCSession BA invite from B and accepts
Time 5 - B gets the confirmation (via the connected event) that A accepted the invitation to MCSession BA
Time 6 - B creates a TCP listener to bridge to the BA MCSession and returns the port for that listener in Node on B
Time 7 - The code in Node on B opens TCP connections on the port returned in time 6 which causes an output stream to be opened by B on MCSession BA which will eventually cause A to be notified of the matching input stream causing B to open an output stream back to A in order to create a virtual socket.

Now let's see if we can agree on some invariants.

Invariant 1 - There is no way for A to initiate an output stream on MCSession BA. A will only create output streams in response to an input stream from A on MCSession BA.

Invariant 2 - There is no way for the B node code to ask for an output stream until after time 6 when it gets the local host port for the TCP listener that will bridge to MCSession BA.

Invariant 3 - There is no way for the port returned in time 6 to be returned before we get the Connected event before Time 5.

If invariants 1-3 are correct then how could we ever create an output stream if we aren't in Connected state?

**Comment by baydet** [comment]
It is possible in the current implementation to create outputStream before the `Connected` state. 
In general because on Browser's side I've implemented it in a slightly different way. 
1. B discovers A
2. B notifies node about A
3. node multiconnect to A
4. B creates MCSession
5. B is waiting for completion of 2 async tasks
 - Creation of virtual socket to B with 5 second timeout.
 - Creation of TCP listener 
6. On these events completion B calls `multiConnectResolved`

There is 2 main differences.
1. We don't wait for `.Connected` but already passing Session to builder asking to create virtual socket with 5 sec timeout. 
2. We're calling multiConnectResolved only when we have both TCP listener and bound to listener TCP socket. 

The main question lays into the second difference. How can we call multiConnectResolved right after `.Connected` session's state but not after creating virtual socket? In this case we will could have racing issue when we're notifying node with port that native is ready but there is no virtual socket linked to TCP listener. It means that we have to put in buffer data from TCP listener and clear it as soon as virtualSocket is ready. But we decided to move this responsibility to node layer.

And to avoid this racing native call multiConnectResolved only with TCP listener and virtual socket are ready.

Anyway, browser's TCP/IP binding wasn't described in a such a detailed way what caused this misunderstanding. We have to update [specs](https://github.com/thaliproject/thali/blob/gh-pages/pages/documentation/PresenceProtocolBindings.md#binding-to-tcpip). I've created thaliproject/thali#277 for this. We have some explanations in thaliMobileNative.js. But I think it deserves mentioning in main native spec.

**Comment by yaronyg** [comment]
So what you describe in steps 1-6 is exactly what the spec says. And point 2 in your differences is what the spec requires. So the only place I see a difference is your comment in point 1 that "We don't wait for .Connected but already passing Session to builder asking to create virtual socket with 5 sec timeout. "

What does that mean? A virtual socket should only be created when we get a connection to the TCP listener and we will only get a connection to the TCP listener as you specified above after step 6 which means that the MCSession is already established and we are in connected mode.

So doesn't this show that we can't get a virtual socket until we are connected?

**Comment by baydet** [comment]
We've made an agreement with @dersim-davaod about how we should change the current codebase to fit specs correctly. @dersim-davaod will provide these changes as part of #881

**Comment by baydet** [comment]
Still fighting with heisenbug in some tests. I've added additional logging for asserts in  #1110 (PR for testing) to be able to see what tests are failing. Unfortunately this process is tremendously slow because of our poor CI (I'm waiting for test result about half an hour in average)

**Comment by yaronyg** [comment]
BTW, if you can get 4 devices in Minsk to pass then we should assume something is wrong with CI.
