### ISSUE TITLE
jxcore: Error!: self.pskIdToSecret is not a function

### ISSUE THREAD

**Issue by artemjackson** [thaliproject/Thali_CordovaPlugin#1060]
Pleese, see the [log](https://raw.githubusercontent.com/ThaliTester/TestResults/85202518d111121__1031_DO_NOT_MERGE_Excluded__bad__test_files_artemjackson/thali04_samsung-SM-G930F.md) for more details.

**Comment by artemjackson** [comment]
We have only two places where `self.pskIdToSecret ` occurs and this error shouldn't appear because of  `ThaliWifiInfrastructure` architecture:
```
ThaliWifiInfrastructure.prototype.start = function (router, pskIdToSecret) {
  var self = this;
  return promiseQueue.enqueue(function (resolve, reject) {
    ...
    self.pskIdToSecret = pskIdToSecret;
    self.states.started = true;
    ...
  });
};
```
```
ThaliWifiInfrastructure.prototype.startUpdateAdvertisingAndListening =
function () {
  var self = this;
  return promiseQueue.enqueue(function (resolve, reject) {
    if (!self.states.started) {
      return reject(new Error('Call Start!'));
    }
    ...
    self.pskIdToSecret(id);
    ...
   }):
};
```
How does this error is possible?!

**Comment by yaronyg** [comment]
What branch is this from? Also this looks like Android so I assume it's Android but it would be good to say. We are going to have to come up with a template for new bugs so we capture this data.

So the error occurred [here](https://github.com/thaliproject/Thali_CordovaPlugin/blob/vNext_yarong_417_812/thali/NextGeneration/thaliWifiInfrastructure.js#L572). I ran a test locally with JXcore SM and I notice that it doesn't distinguish between two error case (e.g. each gets the same error message)

var foo = { bar: 23 }
foo.bar();
foo.blah():

Both will say 'foo.x is not a function'

So either self.pskIdToSecret wasn't set or it was set to something that wasn't a function. Now it's worth pointing out that pskIdToSecret is initialized to null and is only set in the start function.

Now we know this error occurred because we got a request and when we tried to validate the request the function wasn't set up properly. We also know that the function had to be set in start and that we can't actually get requests until startUpdateAdvertisingAndListening is called and we further know that we will throw an error if someone tries to call startUpdateAdvertisingAndListening without first calling start.

I thought, maybe we have a race condition where we could receive a request before we set up the server. But it doesn't look possible. We set the options [here](https://github.com/thaliproject/Thali_CordovaPlugin/blob/vNext_yarong_417_812/thali/NextGeneration/thaliWifiInfrastructure.js#L569) and then start the server [here](https://github.com/thaliproject/Thali_CordovaPlugin/blob/vNext_yarong_417_812/thali/NextGeneration/thaliWifiInfrastructure.js#L577) and only once the server has started do we call the listeningHandler. The listeningHandler is the function that starts us advertising. So we are guaranteed that the server is set up and properly configured before we advertise ourselves. More than that, we also make sure the server is properly configured before we call listen. So even if there was some weird race condition where some old test tried to connect to us and guessed the right port we still shouldn't have seen the error.

So bottom line? We must have been passed in a bad value for pskIdToSecret in thaliWifiInfrastructure.start().

So the question is - what test failed on us and did it pass in a bad value? The error occurred on line 14209 of the log. It looks like the test actually started on line 13994 and is 'should be able to call #startUpdateAdvertisingAndListening many times' Alas the test exists in two different test files (for good reason but we should really distinguish the names, I just created thaliproject/Thali_CordovaPlugin#1065 ) but it looks like testTests.js was the previous test so I assume this error occurred in testThaliMobile.js since it is the next test in order.

Now if we look at that test we see it calls a function called testIdempotentFunction which calls start and only passes in a router, not a pskIdToSecret value. Which would cause our failure.

Now you have to be wondering - why didn't this always fail? The reason is that the test itself doesn't do anything that causes a request to go to the server so the fact that it passed in ull for pskIdToSecret doesn't matter and isn't the bug.

The bug is that somehow, someone, somewhere was running a Thali process, it discovered this Thali process and tried to connect to it. Since I believe this test was running in CI it means either that CI was trying to run tests in iOS and Android at the same time and they ran over each other (totally possible in WiFi only mode) or someone in the Poland office had Thali running and it discovered and connected to the device that failed out. Or the test coordination lost its mind and somehow started one test before the rest had finished. In any case nobody should have connected to the device while this test was running, but they did and kaboom. Bug.

Now I am very worried about this bug showing up in CI because it means something went really wrong. The best case scenario is that someone in Poland was running a test on their own device and were near enough to CI to cause a bad connection. But I need access to the full logs in order to figure out if the tests weren't running in order and someone had managed to run ahead. Or if there was a conflict between IOS and Android tests.

**Comment by artemjackson** [comment]
It's from https://github.com/thaliproject/Thali_CordovaPlugin/pull/1033/commits/d11112113446f2b6383215be28232941f4fe1b47. Ran in CI.

**Comment by yaronyg** [comment]
Given that the tests ran only on Android there really isn't a good reason for the conflict. Where did that spurious request come from? Once we have https://zube.io/projects/3188/tickets/1363 is done then we need to retest.

**Comment by yaronyg** [comment]
@artemjackson Now that the interference free testing is checked in can you please re-run and see if this bug still exists?

**Comment by yaronyg** [comment]
@artemjackson Since anyway the Android folks are going to be re-running all tests I think we should just close this bug for now and we can always re-open it if it happens again.
