### ISSUE TITLE
Investigate / verify that `jx npm run test-coordinated` can be run with node

### ISSUE THREAD

**Issue by larryonoff** [thaliproject/Thali_CordovaPlugin#1111]

**Comment by yaronyg** [comment]
@larryonoff I investigated and you should be able to run it in node. The runner will run in node but the spawn command will run the instances in JX core which is what we want. The only thing I would change is line 113 of runCoordinated Tests where we spawn '../../TestServer/index.js'. We can change that command to 'node' instead of 'jx'. Since the test server should now be running in node. Only the spawned node instances (line 123) should be in JX.
