### ISSUE TITLE
PromiseQueue `# enqueue and run in order` test failure

### ISSUE THREAD

**Issue by artemjackson** [thaliproject/Thali_CordovaPlugin#1113]
`# enqueue and run in order` test failed during the #980 build. It should be fixed so the #980 build passed ASAP.
```
# setup
# enqueue and run in order
ok 145 firstPromise setTimeout
ok 146 firstPromise result
ok 147 firstPromise testValue
ok 148 secondPromise setTimeout
ok 149 thirdPromise in promise
ok 150 secondPromise result
not ok 151 secondPromise testValue
  ---
    operator: equal
    expected: 100
    actual:   1000
    at: tryCatcher (/Users/thali/Github/Thali_CordovaPlugin/thali/node_modules/bluebird/js/release/util.js:16:23)
  ...
ok 152 thirdPromise result
ok 153 thirdPromise testValue
```

Please see the [log](https://github.com/ThaliTester/TestResults/blob/8362571365361c0__973_Added_thaliPromise_artemjackson/build.md) from the CI build for more datils:

**Comment by yaronyg** [comment]
@artemjackson Um.... uh... how can a test like that just start failing? Unless Bluebird has different behavior than Lie? Which is a thought that chills my bones. But I thought that you weren't going to check in thaliproject/Thali_CordovaPlugin#980 because you were just going to hardcode Bluebird everywhere? I'm confused.

**Comment by artemjackson** [comment]
The PR #980 where the issue was discovered is closed.
