### ISSUE TITLE
bluebird.config error during running coordinated tests

### ISSUE THREAD

**Issue by dersim-davaod** [thaliproject/Thali_CordovaPlugin#1158]
see log in https://gist.github.com/dersim-davaod/8808bf1bef3516e4d7ac44e1ebdb4336

**Comment by yaronyg** [comment]
What branch is this from?

**Comment by artemjackson** [comment]
@yaronyg it's superbranch [1f257d1](https://github.com/thaliproject/Thali_CordovaPlugin/tree/1f257d1dd50ca7d85eccc4b716065fdf49b4afa0) before bluebird issue hotfix (#1154)

**Comment by yaronyg** [comment]
@andrew-aladev if you look [here](http://bluebirdjs.com/docs/api/promise.longstacktraces.html) it says at the top that you can't turn Long stack traces on after promises have been enabled. So we have some kind of ordering issue. But I'm not completely sure what would have caused it since a require only loads a module exactly once. So requiring Promise.js multiple times shouldn't be a problem. So it seems like there are two fairly obvious possibilities:

1. We are somehow loading Promise.js from two different locations in the same process. This seems unlikely but it's not impossible.
2. What happens if we loaded lie and then loaded bluebird? Or, better yet, what would happen if we loaded lie, created a promise and then loaded bluebird? If the two different promise types ever crossed each other normally they would interoperate but what happens with long stacks?

**Comment by artemjackson** [comment]
> We are somehow loading Promise.js from two different locations in the same process. This seems unlikely but it's not impossible.

Actually it's the reason of the failure. `Bluebird` is explicitly required in the `testUtils`, see [here](https://github.com/thaliproject/Thali_CordovaPlugin/blob/vNext_yarong_417_812/test/www/jxcore/lib/testUtils.js#L11). It causes the failure.

BTW the #1197 solves the issue completely.
