### ISSUE TITLE
Test 'Coordinated replication action test' failed on Android

### ISSUE THREAD

**Issue by evabishchevich** [thaliproject/Thali_CordovaPlugin#1187]
Logs
https://gist.github.com/evabishchevich/e9a6df4ee0eb53aaa15b288c7389c155

Branch: vNext_yarong_417_812_848, commit:  b689f01 
https://github.com/thaliproject/Thali_CordovaPlugin/commit/b689f01e9a6c902a6f0eee38bb6928770ffbd60f
This test fails randomly.

**Comment by yaronyg** [comment]
@andrew-aladev Take a look at the second device's error! If I'm reading it correctly our TLS client failed out because it couldn't negotiate a session with the server! We don't have the full logs for the other devices so I can't see if it's something easy like us sending the wrong name/secret with PSK. The other possibility is that somehow PouchDB decided to either use HTTP or vanilla HTTPS. Or somehow the server itself isn't set up correctly. The fact that it fails only intermittently argues that this is some kind of error in the test itself.

**Comment by yaronyg** [comment]
This is the same bug we saw with thaliproject/Thali_CordovaPlugin#1182, it has not repo'd today.

**Comment by vasilevskayaem** [comment]
tested 15 times on master branch with "jxcore-cordova-url": "http://jxcore.azureedge.net/jxcore-cordova/0.1.4-v8/release/io.jxcore.node.jx", can't reproduce

**Comment by enricogior** [comment]
I can't repro using current 'master'.

**Comment by yaronyg** [comment]
No repo.
