### ISSUE TITLE
test if it is possible for iOS device to act like peripheral in background

### ISSUE THREAD

**Issue by baydet** [thaliproject/Thali_CordovaPlugin#1422]

**Comment by baydet** [comment]
I've made a check on iOS 10 and it looks like device as BLE peripheral is working in background!
One thing to keep in mind: app should be in the stack of the opened apps. If will remove it app will stop advertising.
Now I'm going to check if it is possible to establish multipeer connection as part of the background task. And it looks like we have no possibility to perform this connection. There is no answer in Apple's docs as usual but "some man from internet" is saying that we have only 5 seconds to do some nasty things in background. And I'm really not sure that during this time app can event initialize the whole JX stack. I'm not saying about establishing MPC connection

**Comment by drinkius** [comment]
Background discovery works in the background, tested with iOS 9.3.3/iOS 9.3.5/iOS 10.1.1 devices - all combinations of devices are able to discover each other while both are in background, tests performed with unchanged version of [**Bubble Chat**](https://github.com/softwarenerd/BubbleChat) example app.

Background data transfer also works well, test performed with [**BluetoothKit**](https://github.com/rhummelmose/BluetoothKit) example app, Swift 3 version. Data transfer functionality added by setting up a timer in _RemotePeripheralViewController_ which calls _sendData()_ method every 5 seconds. While both apps go into background mode - transfer doesn't stop for 3 minutes while they are still active. This time period most likely can be extended with the use of background tasks, which themselves have 180s of execution time and can be called upon peripherals discovery/connection

**Comment by drinkius** [comment]
## Background discovery
### Environment
* iPhone 6s -iOS 10.1.1
* iPhone 6s -iOS 10.1.1
* iPhone 5s -iOS 9.3.5
* Unchanged version of [**BubbleChat**](https://github.com/softwarenerd/BubbleChat) example app

### Results
I’ve run a completely clean install of BubbleChat on all the devices, after the install I went from the app to home screen, locked the device and put it into signal-cancelling faraday cage. After that I’ve pulled all the devices out of isolation and in the first run, for some reason, no devices could see each other. After I unlock the device and put app in the foreground - the mutual background discovery works perfectly with any other device.

After that I’ve deleted the apps from all three devices, reinstalled it with the same steps reporduced, and after that one of the iOS 10 devices could see the iOS 9 device and raise a notification, iOS 9 device was silent. Looking into logs - it seems that the iOS 10 device was running a central role, so iOS 9 must have been peripheral, in it’s logs I could see only two simple mentions of Bluetooth operations:

  _kernel[0] <Notice>: system wake events:bluetooth
powerd[35] <Notice>: Wake [CDNVA] due to bluetooth:_

Which seem to be unrelated to the discovery events. From this I assume BLE in iOS 9 peripheral was using hardware handoff of BLE UUIDs, and the discovery of it by another device didn’t call any app’s delegate methods. The iOS 10 device which was able to discover the iOS 9 device was the last one to be locked and I still am to figure out if the order does have any effect on the output.

My previous test were run between iPhone 5s with iOS 9.3.5, iPhone 5 with iOS 10.1.1 and iPad Pro 10in with iOS 9.3.3. The discovery seemed to work better with that setup, I tried making app reinstalls every time and devices could discover each other on the first start. I have to rerun the tests to figure out if there were some other factors contributing to the successful tests results in my previous setup.

**Comment by yaronyg** [comment]
There is a limited effect where if two devices have very recently (under an hour) discovered each other via BLE in the foreground then they will continue to discover each other in the background but if anything funny happens, enough time passes, the app gets reset, somebody went in and out of airplane mode (thus deactivating bluetooth), etc. it won't work. So it's nothing we can really depend on at best it is an edge case enhancement.
