### ISSUE TITLE
iOS branch is broken

### ISSUE THREAD

**Issue by baydet** [thaliproject/Thali_CordovaPlugin#1428]
I'm guessing this commit is the reason: https://github.com/thaliproject/Thali_CordovaPlugin/commit/28c2c11012899bcabe471aae354b3c89d4155cea 

Logs: https://gist.github.com/baydet/adfcf338169a8f71aff7397b36ababd9

**Comment by larryonoff** [comment]
### Reason of the issue

The issue occurs because of two reasons:
1. `ANDROID_HOME` variable isn't set.
2. `validateBuildEnvironment.js` doesn't check that `ANDROID_HOME` is defined and uses this variable. So it reports and error `Environment not valid: TypeError: Path must be a string. Received undefined`.

### Solution

1. add the command below ```export ANDROID_HOME="`brew --prefix`/opt/android-sdk"``` into your: .bashrc, .zshrc, etc.
2. `validateBuildEnvironment.js` should check that  `ANDROID_HOME` is set.

**Comment by larryonoff** [comment]
I just noticed that on CI we don't have necessary logs to understand where and how validateBuildEnvironment.js failed.

**Comment by larryonoff** [comment]
created PR thaliproject/Thali_CordovaPlugin#1436

**Comment by larryonoff** [comment]
I have identified the issue. CI has outdated jxcore installed, i.e. 0.3.1.2, when 0.3.1.5 should be.

**Comment by larryonoff** [comment]
created issue to update jxcore, see thaliproject/CI#82

**Comment by larryonoff** [comment]
created issue to update jxcore on CI thaliproject/CI#82

**Comment by larryonoff** [comment]
update Jxcore on CI should be the only remained issue to resole this issue.

**Comment by larryonoff** [comment]
I'm closing it, because we made some script fix and updated CI. Please note that for now we have disabled `validateBuildEnvironment.js`.

**Comment by yaronyg** [comment]
@larryonoff What is the bug to track that validateBuildEnvironment isn't working and needs to be fixed?

**Comment by larryonoff** [comment]
@yaronyg there's only PR, see thaliproject/Thali_CordovaPlugin#1436. It's fixed already.
