### ISSUE TITLE
ThaliMobileNativeWrapper ignores peer availability information when recreating listeners

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#1446]
Scenario:
1. We get a peer availability announcement for peer foo
2. We enqueue an action to connect to peer foo
3. We get a peer not available announcement for peer foo
4. The action enqueued in step 2 fires and fails
5. createPeerListener will fail on the connection (the peer isn't there) and fire a listenerRecreatedAfterFailure which goes to thaliMobileNativeWrapper who fires a nonTCPPeerAvailabilityChangedEvent which leads to us creating a new listener and firing a peerAvailabilityChanged event asserting the peer is still around

Expected Outcome: We would realize that the peer isn't there and short circuit the listenerRecreatedAfterFailure event

Actual Outcome: We first it without any regard for any peer not available announcements

The idea behind listenerRecreatedAfterFailure is that so long as the peer is available we should keep creating listeners for them even after failed connections, otherwise there is absolutely no way to retry failed connections. Note that this is a temporary issue because once we switch to the new design and introduce the getPeerHostInfo then the entire listenerRecreatedAfterFailure feature just goes away. Instead if a connection fails then the caller just calls getPeerHostInfo again. So whatever we do is just a band aid.

So in the interests of keeping things simple what we can do is:
1. Write a test to confirm the problem
2. Add a field 'recreatedAfterFailure:true' to the peer emitted in the nonTCPPeerAvailabilityChangedEvent in thaliMobileNativeWrapper.listenerRecreatedAfterFailureHandler 
3. In thaliMobile's ThaliMobileNativeWrapper.emitter.on('nonTCPPeerAvailabilityChangedEvent put in a check to see if the peer has recreatedAfterFailure: true and if so then check peerAvailabilities to see if it has the peer marked as not available. If it does then just dump the peer.

**Comment by yaronyg** [comment]
But in any case the first thing we need to do is write a test that confirms the bug exists and will also confirm when we fix it.

**Comment by chapko** [comment]
> if the peer has recreatedAfterFailure: true and if so then check peerAvailabilities to see if it has the peer marked as not available. If it does then just dump the peer.

It wouldn't work. TcpServersManager fires 'failedConnection' right before recreating listener. This event then translates into 'nonTCPPeerAvailabilityChanged' with `peerAvailable: false`. So when we get 'peerAvailabilityChanged' event after recreation, the corresponding peer will be already nuked from cache.

But what I see right now it 'test write' tests log output is that

1. We get peer availability announcement for peer *foo* - this creates peerListener on port 33333
2. We enqueue a notification action for this peer
3. We start this action, which sends https request to the 33333 port
4. We get a peer not available announcement for peer *foo*, because this peer called `startUpdateAdvertisingAndListening` and it's now *bar*, not *foo*.
5. At this point we come to the actual `Mobile('connect')` call for the peer foo and it fails.
6. `createPeerListener` closes its listener, emits 'failedConnection' (which translates to the second peer unavailability announcement) event and restarts listener asynchronously.
7. And only then we successfully recreate our listener and fire 'peerAvailabilityChanged' event with a new port for the non-existent peer *foo*.

I think it is better to put some flag in the 'nonTCPPeerAvailabilityChanged' fired from 'failedConnection' event.

I was messing around with it in `master_chapko_1446` and it looks like it works.

**Comment by yaronyg** [comment]
First off, good catch. The reason for all this is because Wifi and Android used to send tons of redundant peerAvailabilityChanged events so we didn't need to worry about peers 're-appearing'. But at least with Android that is no longer true.

Second, I wrote a test to make sure we fail properly. Basically if we cannot connect to a peer that was advertised with a peerAvailabilityChanged from thaliMobile then we should get two new peerAvailabilityChanged events, one that says the peer is not available (this tells everyone the previous advertised port is no good) and then a second saying that the peer is available at the new port. This test turned up a bug where we would actually advertise that a peer wasn't available twice in the previous case. It was a simple if statement to fix.

Third, I like your general idea for how to handle this mess. What we need to do is to get handlePeer in thaliMobile to:
1. If it receives a nonTCPPeerAvailabilityChangedEvent announcing a peer isn't available as the
result of a recreated action then we have to check cache. If there is no entry in the cache then
the peer has already been declared to not be available so we can ignore the announcement. If the peer is in the cache then we will emit the event BUT we won't change the cache.
2. If it receives a nonTCPPeerAvailabilityChangedEvent announcing a peer is available as the result of a recreated action and the peer is not in the cache then we will ignore the event and call terminate on the server. If the peer is in the cache then we will emit the event but we won't update the cache.
