### ISSUE TITLE
Remove updateAndroidSDKVersion function in after_plugin_install.js

### ISSUE THREAD

**Issue by evabishchevich** [thaliproject/Thali_CordovaPlugin#1560]
We could replace updateAndroidSDKVersion function with the next config in plugin.xml, couldn't we?
```xml
<edit-config file="AndroidManifest.xml" target="/manifest/uses-sdk" mode="merge">
    <uses-sdk android:minSdkVersion="21" />
</edit-config>
```
We've discussed this question a week ago but I didn't catch what should be a replacement for that function.  @yaronyg Could you please explain, why we still use variables like ORG_GRADLE_PROJECT_cdvMinSdkVersion?

**Comment by evabishchevich** [comment]
And we have to use 
```xml
<engine name="cordova-android" version=">=6.0.0" />
```
for edit-config working

**Comment by larryonoff** [comment]
just a reminder that if decide to stick with environment variables, we'll need to update README.md that these variables should be set.

**Comment by evabishchevich** [comment]
@yaronyg  Any updates? We still think that it's good idea to use config, not an environment variable

**Comment by yaronyg** [comment]
Check that all three environment variables we are using can be successfully set using edit-config. If so then just check if the environment variable overrides edit-config and decide if we care.

**Comment by yaronyg** [comment]
We want to set three values that will control both our Android build as well as what kinds of apps can use us. Those three values are: minSdkVersion, BuildToolsVersion and CompileSdkVersion.

#### minSdkVersion and AndroidManifest.xml
One of these values, minSdkVersion is set in AndroidManifest.xml of the final Android project. However the AndroidManifest.xml file is dynamically created by Cordova during build time so we can't just shove the values in that file.

Instead we have to indicate somewhere else what values we want and then get Cordova to set the values for us.

Cordova supports two different approaches to setting this value. 

One approach is to use the edit-config command in the Cordova plugin.xml file where we specify what amounts to the moral equivalent of an xpath saying "Set this attribute on this element in AndroidManifest.xml to this value." and as a side effect of giving this command we get minSdkVersion set how we want. This is all documented btw in http://cordova.apache.org/docs/en/6.x/plugin_ref/spec.html#edit-config.

The other approach to setting minSdkVersion I'll describe in the next section because it applies to our other two values as well.

#### BuildToolsVersion and CompileSdkVersion

These two values both have to be set in the build.gradle file of the final Android project. This file is itself generated by Cordova and so we can't just stick values in there since there is no 'there' until the file is generated.

Cordova's has four ways it supports setting these two values as defined in https://cordova.apache.org/docs/en/latest/guide/platforms/android/#setting-gradle-properties. As a side note it runs out that Cordova also supports using Gradle properties to set minSdkVersion in the AndroidManifest.xml file.

Right now we use choice 1 and we validate that this choice is successfully configured in validateBuildEnvironment. But I recognize that this is sub-optimal because it means having to set fiddly environment variables in random places which is annoying.

I think we can also skip choice 2 as I doubt we want to require people to have to pass magic flags during build (even though we could hard code this into setUpTests.sh) and hides these important values in setUpTests.sh which is just odd and anyway won't work right when we finally stop using our test infrastructure for setting things up and instead use a normal production infrastructure.

So if we want to use this approach we are left with choices 3 or 4. Both of which really suck. In both cases we have to create magical files (either gradle.properties or build-extra.gradle) somewhere in our depot and then use before_build or some other Cordova hook to copy them over to the final project. Ick!

To make matters worse we actually do this today but in a way that is going to create a mess. We have a build-extras.gradle in both our mainline and in our test code. But right now we only have logic that copies over the test version. This is going to lead to serious headaches down the road.

#### So what do we do?

I think we can rule out edit-config since it only handles minSdkVersion. Using gradle properties, through one of the four listed ways, lets us solve for all three values.

We currently use #1 and I understand why we don't like that. Setting environment variables is fiddly under the best of circumstances.

Option #2 isn't any better. It requires setting magic values and keep in mind that currently the only place we have to set those values is in setUpTest.sh which is only supposed to be used for testing. So for production we would have to tell people to include the magic values as command line options. Ick.

So this leaves Options #3 and #4. That is, we can either stick these values into gradle.properties or into build-extras.gradle.

Investigating these two options opened up a world of problems. In the case of build-extras.gradle we actually already have two. One under src/android/java and the other under src/android/test. To make things worse it turns out that we exclusively use the second one, not the first one and we install it in after_plugin_install.js in a command called copyTestFiles/copyBuildExtrasGradle.

Now the good news is that we only copy over the test version if we detect that we are running Android unit tests. So in production we won't copy the test version. Unfortunately in production we also don't copy the production version! And to make things more complex we really need the same values for our three variables regardless of if we are doing production or testing. So I think we should avoid build-extras.gradle. It is just going to cause confusion.

That then leaves us with gradle.properties. The good news is that we actually already use that file. The bad news is that we dynamically generate it [here](https://github.com/thaliproject/Thali_CordovaPlugin/blob/da2e96f7eccbd9dbd6362037dc39182abd551c4c/thali/install/install.js#L347).

This leaves us with two choices:
Choice #1 - We can create an actual gradle.properties file and stick stuff in there
Choice #2 - We can continue dynamically generating the gradle.properties file

I actually want to go with choice #2 and the reason is that the value we currently put in gradle.properties (which is the version of btconnectorlib2 we are supposed to use) actually comes from a property bag in our package.json. I really like the idea of dumping as many things in there as humanly possible so as much config as is reasonably can be in a single place.

#### I'm sorry, what EXACTLY are we supposed to do?!?!?!?!
1. Edit package.json's thaliInstall object to add three new values, minSdkVersion, BuildToolsVersion and CompileSdkVersion. Each will have a number as its value.
2. Edit install.js to:
 1. Set minSdkVersion, buildToolsVersion and compileSdkVersion variables based on the values in package.json
 2. In the section where we generate gradle.properties insert a line for btconnectorlib2Version, cdvMinSdkVersion, cdvBuildToolsVersion and cdvCompileSdkVersion.
3. Edit validateBuildEnviroment to remove the cordovaAndroidSetMinSDK, cordovaAndroidSetBuildToolsVersion and cordovaAndroidSetCompileSdkVersion entries

**Comment by yaronyg** [comment]
My fix plain don't work. That's what I get for not more carefully checking the build file. :(

**Comment by yaronyg** [comment]
O.k. so it isn't that easy. Sigh... by switching all the config over to Cordova I can't seem to build in Android Studio. I have to build using Cordova. I did rip open the AndroidManifest.xml and it did show it building (platformBuildVersionCode) with the right version. Which is not as trivial as it sounds as the default build version on my machine is a higher SDK number as is the default version specified in the project (but not in the Cordova config). So for now I have to assume that Cordova is behaving itself and I just have to build that way.
