### ISSUE TITLE
Mobile().registerToNative should be called only once

### ISSUE THREAD

**Issue by chapko** [thaliproject/Thali_CordovaPlugin#1611]
`registerToNative` method has different logic on iOS and Android.

https://github.com/thaliproject/jxcore-cordova/blob/master/app/jxcore_cordova.js

```javascript
JXMobile.prototype.registerToNative = function(target) {
  if (!isAndroid)
    process.natives.defineEventCB(this.name, target);
  else
    JXMobile.events[this.name] = target;
  return this;
};
```

But mock does not handle platforms differently and always overrides old callback for the same event. That behavior breaks many tests.

My proposal is to use dumbest event emitter that just passes through native events. It allows to use multiple listeners for the same event and unsubscribe from events.

**Comment by yaronyg** [comment]
Per our conversation today the difference in behavior in iOS vs Android shouldn't be visible to us. The behavior we see is the same, which is that registerToNative events should only go to the last callback that registered for them. So there should be no differences on iOS vs Android and in fact we don't see any differences in the test. The issue that caused us to worry about this is that we are having an iOS test that is failing because someone else grabbed registerToNative in a previous test. But that is just a clean up problem. We need to make sure that any file that messes with registerToNative must call thaliMobileNativeWrapper._registerToNative before exiting.
