### ISSUE TITLE
testNativeMethod.js tests fail with 'unexpected result' error

### ISSUE THREAD

**Issue by chapko** [thaliproject/Thali_CordovaPlugin#1619]
These tests are designed to perform checks after the test end.

**Comment by yaronyg** [comment]
I checked in the fix for this test to iOS_1620. But right now the test 'onPeerLost calls jxcore' fails because the check for callbackPeer.generation is supposed to be null in this case but actually returns 0. This should be a bug in the native code. Please fix and then we can confirm it works and close this issue.

**Comment by evabishchevich** [comment]
PR thaliproject/Thali_CordovaPlugin#1651
