### ISSUE TITLE
Why multiConnectConnectionFailure event is emitted after a call to `disconnect`?

### ISSUE THREAD

**Issue by chapko** [thaliproject/Thali_CordovaPlugin#1675]
```JavaScript
/**
 * Identifies the peerID of the peer with whom a `multiConnect` initiated
 * connection (read: MCSession) failed.
 *
 * @public
 * @callback multiConnectConnectionFailureCallback
 * @property {string} peerIdentifier
 * @property {string} error
 */

/**
 * Fires the multiConnectConnectionFailureCallback if a multiConnect connection
 * fails. This failure can include a failure induced by a call to `disconnect`.
 * Note, however, that this callback MUST only occur in response to an actual
 * connection being terminated. So, for example, if disconnect is called with
 * a peerID that isn't in the connected state then the disconnect will be
 * successful but because no actual MCSession was terminated there won't be
 * a multiConnectConnectionFailureCallback.
 *
 * @public
 * @function external:"Mobile(`multiConnectConnectionFailure`)".registerToNative
 * @param {module:thaliMobileNative~multiConnectConnectionFailureCallback} callback
 */
```
We need to distinguish between `multiConnectConnectionFailure` caused by disconnect and `multiConnectConnectionFailure` caused by error.

Do we really need to fire `multiConnectConnectionFailure` as a result of a `disconnect` call? Because it doesn't feel like a failure. In this case we don't need to make any distinguishing.

Or should we think about `multiConnectConnectionFailure` as if it was named `multiConnectConnectionTerminated`? In this case `disconnect` will eventually emit `multiConnectConnectionFailure` with `error: null`.

**Comment by yaronyg** [comment]
We use this event to fire a new peerAvailabilityChanged event from thaliMobile because currently our code (wrongly) depends on such events after getting a session failure. So we do need to fire this even for a call to disconnect or that new peerAvailabilityChanged event won't get fired and we won't ever be able to connect to that peer again.

Yes, this is a bug in a sense and we should really change to a model where people retry to connect to peers by just calling getPeerHostInfo but as we discussed that would require changes in a bunch of places that we don't have time for right now.
