### ISSUE TITLE
"can get data from all participants" fails on iOS devices in native mode

### ISSUE THREAD

**Issue by dersim-davaod** [thaliproject/Thali_CordovaPlugin#1755]
Logs from device is [here](https://gist.github.com/dersim-davaod/11e648fa055d79c812ce7f524bff7415).

**Comment by drinkius** [comment]
Test execution stops after **getPeerHostInfo** request which is executed and does return the data and before the **.then(function (uuid)** part, which never gets called. At the same time the peers do connect to each other according to the currently produced logs.

I've run the test with additional logging to see if the data is actually sent/received over MPCF and is further sent/received on the Node layer. Logs can be found [here](https://gist.github.com/drinkius/e6283d9a83315880d6f88ac57087ce13) and it seems that on the native part the data is exchanged the way it's expected to work, currently consulting with the Node guys to see what could be the issue

**Comment by chapko** [comment]
I've created two new very simple data transfer tests, the first one ('Can shift data') uses `net.Socket` and the second one ('Can shift data securely') uses `tls.Socket` with PSK (branch [`master_chapko_minidatashifttest`](https://github.com/thaliproject/Thali_CordovaPlugin/tree/master_chapko_minidatashifttest)).

'Can shift data' always passes on devices but 'Can shift data securely' hangs. It looks like it can't finish handshake, in the logs I see that tls module writes 116 bytes into the underlying `net.Socket` but then does not receive anything. It should receive 75 bytes back, at least that's how it works on desktop.

Logs are available here: https://github.com/chapko/thali-logs/tree/ios-tls-handshake-fail

**Comment by yaronyg** [comment]
This looks like a job for @orangemocha and @enricogior

**Comment by enricogior** [comment]
I'll investigate it tomorrow.

**Comment by enricogior** [comment]
@chapko please add details on how to configure the test environment and what command to use to get the same results you reported.
I tried running `jx runCoordinatedTests.js  --networkType=NATIVE --filter bv_tests/testThaliMobileNative.js ` but it produces a different output from what you put in https://github.com/chapko/thali-logs/tree/ios-tls-handshake-fail
Thanks.

**Comment by chapko** [comment]
@enricogior I've updated this test on Friday, so it prints now all the encrypted traffic between node and native. Logs above are from b27d9b300fcfaa4b7b1e8b71badf8e8739573919 commit.

To run only those 2 tests on devices I used this patch https://gist.github.com/chapko/00fd9beaa423f39acfa372c63da7702b. I can update a bit later (in ~1hr) the branch itself so it can be done with just `./build.sh`

**Comment by enricogior** [comment]
@chapko yes please update the branch, I'm working on other things now and I can wait.
When you run on devices, does it require two devices?
In case please push all configuration changes you have on your local repo.

**Comment by chapko** [comment]
Ok, will update it asap

On Mar 21, 2017 2:06 PM, "Enrico Giordani" <notifications@github.com> wrote:

@chapko <https://github.com/chapko> yes please update the branch, I'm
working on other things now and I can wait.
When you run on devices, does it require two devices?
In case please push all configuration changes you have on your local repo.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/thaliproject/Thali_CordovaPlugin/issues/1755#issuecomment-288045935>,
or mute the thread

**Comment by enricogior** [comment]
I used chaplo's simplified test https://github.com/chapko/jxcore-tls-test to verify the problem sending data from iOS to Android and viceversa, without errors.
So the problem might be caused by some steps that are present in the original test but not in the simplified version.
At least now we know that the basic tls functionality on iOS is not broken.

**Comment by enricogior** [comment]
I'm currently stuck on a libuv write that seems to complete successfully but the data is not received by the mpcf's TCPClient.
This is the call in libuv:
https://github.com/thaliproject/jxcore/blob/master/deps/uv/src/unix/stream.c#L757
It returns the correct number of bytes to be written (266).
It occurs after the device that is acting as a server has completed successfully his part of the SSL handshaking, while the client hasn't yet completed the final stage of the handshake.
Is it possible that the TCPClient somehow stops working because the stream has been 'secured' during the SSL handshake?
