### ISSUE TITLE
Thali doesn't work after switching off WiFi

### ISSUE THREAD

**Issue by mlesnic** [thaliproject/Thali_CordovaPlugin#1823]
The scenario is the same as in #1822, but instead of crash, we do just do not see any replications at all. 
What is interesting is that we can see in logs that there is indeed some data exchange by bluetooth, but in the end, we don't see changes on the other device.

Here are some logs:
[S7_1](https://gist.github.com/mlesnic/c3269795792b2b4890cb8bcef1a953b4)
[S7_2](https://gist.github.com/mlesnic/dfdaddf0282bef5436333e621d511780)

**Comment by mlesnic** [comment]
In our TeamONE application, what is interesting, that it starts working again after turning back WiFi on, so it looks like BT replication doesn't work or works really poorly.

**Comment by mlesnic** [comment]
Today using our custom peerPool I managed to make it work via Bluetooth only after switching off wifi. BUT. After turning it back on, so the phones connected again to this WiFi, replications were only via Bluetooth! After thali restart, it started working again via Wifi and Bluetooth.

**Comment by chapko** [comment]
There was one more problem that sometimes delayed emitting updates for 4-5 minutes (!). When checking if wifi network is available ThaliWifiInfrastructure used only device wifi state (enabled/disabled) and ignored the scenario when device WiFi radio enabled but it is not connected to any access point.

So when device got *networkChanged* event it tried to restart SSDP server and client. Since device wasn't connected to access point, node-ssdp couldn't start advertising and listening, but what even worse is that single restart with disabled network could take a long time. So having several `startUpdateAdvertisingAndListening` calls in the queue could block any updates for a long time.
