### ISSUE TITLE
Inconsistency in 'multiConnectToPeer' and 'disconnect' APIs

### ISSUE THREAD

**Issue by enricogior** [thaliproject/Thali_CordovaPlugin#1874]
[`multiConnectToPeer`](https://github.com/thaliproject/Thali_CordovaPlugin/blob/411576925e169b8546762c74a75c4e750c5d125b/src/ios/AppContext.swift#L347) input parameter is the peer `uuidIdentifier` without the generation id.
[`disconnect`](https://github.com/thaliproject/Thali_CordovaPlugin/blob/411576925e169b8546762c74a75c4e750c5d125b/src/ios/AppContext.swift#L400) input parameter is the peer id composed by the `uuidIdentifier` followed by the generation id.

I would like to understand if there is a reason why the generation id is not passed to `multiConnectToPeer`? The generation id is available in the node layer when `multiConnectToPeer` is called.

Moreover, in [`BrowserManager.connectToPeer`](
https://github.com/thaliproject/thali-ios/blob/master/ThaliCore/MultipeerConnectivity/BrowserManager.swift#L154) we have to keep track of the most recent generation id for the input peer `uuidIdentifier` because it is not passed as input parameter.
In my opinion, that mechanism of retrieving the generation id is a potential bug since there is no guarantee that the retrieved generation id matches the generation id originally received in the node layer.

**Comment by yaronyg** [comment]
I believe the logic went something like this: When we discover a peer with UUID Foo and generation 0 we want to connect to them. We don't care if from the time we sent the multiconnect to when the native call is made that the generation for Foo might have increased to 2 or 3 or whatever. The reason we don't care is that the generation just says "I have new data". So if we wanted to connect to Foo with generation 0 then we really want to connect to Foo with a higher generation since it means it has more new data. So we don't specify the generation on multiconnect because it doesn't matter.

Now disconnect is weird. And I think we may just have a bug. If you notice we specify [here](https://github.com/thaliproject/Thali_CordovaPlugin/blob/ac3ab6aef6895357b0232653da02a624e889e1f9/thali/NextGeneration/thaliMobileNative.js#L384) that disconnect is supposed to get a peerIdentifier. But peerIdentifier is defined [here](https://github.com/thaliproject/Thali_CordovaPlugin/blob/ac3ab6aef6895357b0232653da02a624e889e1f9/thali/NextGeneration/thaliMobileNative.js#L533) and note how it explicitly states that in the iOS case only the UUID and not the generation is supposed to be returned. And in fact we double down on this [here](https://github.com/thaliproject/Thali_CordovaPlugin/blob/ac3ab6aef6895357b0232653da02a624e889e1f9/thali/NextGeneration/thaliMobileNativeWrapper.js#L777) which is the higher layer wrapper which explicitly says that peerIdentifier is the value taken from peerAvailabilityChanged which as we already specified is only supposed to return the UUID and not the generation.

And yet we can see [here](https://github.com/thaliproject/Thali_CordovaPlugin/blob/ac3ab6aef6895357b0232653da02a624e889e1f9/src/ios/AppContext.swift#L404) that we are going to pass the identifierString as a constructor to a Peer object. Which we can see [here](https://github.com/thaliproject/thali-ios/blob/master/ThaliCore/Core/Peer.swift#L100) will actually throw if we don't specify the full UUID + generation.

All of which leads to a fairly depressing discovery. If we check [here](https://github.com/thaliproject/Thali_CordovaPlugin/blob/ac3ab6aef6895357b0232653da02a624e889e1f9/test/www/jxcore/bv_tests/testThaliMobileNativeiOS.js) we see that we never actually use disconnect in any real test with a real connection.

So the reason this bug was never found is that near as I can tell there doesn't exist even ONE test where we connect over iOS and then disconnect.

**Comment by enricogior** [comment]
Thanks @yaronyg, I'll go ahead and fix it removing the generation id from the `disconnect` API implementation.

**Comment by enricogior** [comment]
@yaronyg the disconnect bugs are tracked [here](https://github.com/thaliproject/Thali_CordovaPlugin/issues/1875)
There are actually two bugs, one is the fact that the API has been implemented expecting a uuid + a generation id, the other is that the call fails silently if a malformed peer id is passed.
We can close this issue.
