### ISSUE TITLE
Test: remove thaliMobileNativeWrapper._registerToNative() in 'teardown'

### ISSUE THREAD

**Issue by enricogior** [thaliproject/Thali_CordovaPlugin#1883]
The call [`thaliMobileNativeWrapper._registerToNative();`](https://github.com/thaliproject/Thali_CordovaPlugin/blob/master/test/www/jxcore/bv_tests/testThaliMobileNative.js#L53) in `teardown` is not necessary unless it has been added to workaround some bug that I'm not aware of.

**Comment by jareksl** [comment]
Similar code was added also in other tests. Please see the commit below:  https://github.com/thaliproject/Thali_CordovaPlugin/commit/714611f7ecc68c7843c9a9b8cef1dbb25d339052
It was done in order to restore unregistered functions, but i don't know if it is possible to unregister the function during the test.

**Comment by enricogior** [comment]
If a test needs to un-register and then re-register in `teardown` it should be done explicitly setting a global variable (i.e `callRegisterToNativeInTeardDown = true`) so the call to `thaliMobileNativeWrapper._registerToNative();` is only done when strictly needed.

**Comment by mlesnic** [comment]
Actually, we need to call it in teardown, because using `executeZombieProofTest` function means that we overwrite a default handler for `peerAvailabilityChanged` event. So if we would not register again default one, other tests that rely's on this will fail.
