### ISSUE TITLE
ThaliCore: invitePeer timeout value 

### ISSUE THREAD

**Issue by enricogior** [thaliproject/Thali_CordovaPlugin#1884]
The [`invitePeerTimeout`](https://github.com/thaliproject/thali-ios/blob/93f254222ce2585d1d17f6296001f51300584e70/ThaliCore/MultipeerConnectivity/Browser.swift#L28) value is set to 30 seconds.
That timeout is reached when a zombie advertiser is present or the devices move away and are not anymore visible to each other. In both cases it would be preferable to have a shorter time out, something around 5 seconds or less.

@yaronyg do you agree?

**Comment by yaronyg** [comment]
The reason we had a long time out is because Bluetooth often behaves very, very badly. So if we put too short of a timeout we would think the peer was dead when they weren't. So I have no fundamental problem with shortening the timeout but we have to make sure it doesn't cause us to falsely miss peers.

**Comment by enricogior** [comment]
@yaronyg "Bluetooth often behaves very, very badly" on iOS?

**Comment by yaronyg** [comment]
Sorry, I didn't hit the link. I thought this was the higher level timer we had in the Node code. I didn't realize this was the iOS code. My bad. It's what I get for doing an issue review while distracted. Obviously turning it down to whatever works is fine.

**Comment by enricogior** [comment]
Fixed in https://github.com/thaliproject/thali-ios/commits/master-enrico-error-handling-tmp
