### ISSUE TITLE
Test the iOS unit and perf tests for CI

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#189]
As part of the CI work we made changes to the tests that may have made iOS's tests not run.

**Comment by vjrantal** [comment]
Current status is that app deployment to iOS fails in the CI https://gist.github.com/ThaliTester/1be6e683616ebc7fe5f9.

Due to not being able to see all the logs it hard to tell what goes wrong. I have verified that when I run the same command CI uses (for app deployment) locally, the deployment succeeds. However, it takes quite a bit of time due to the massive number of files we have in the app that there might be some timeouts in the CI that we are hitting.

**Comment by vjrantal** [comment]
Status:
* iOS tests can be run in CI, but not all of them pass - not even locally
* For perf tests to work, it requires a test loading fix that while writing this is only available in story_001_juksilve branch
  * Will work "out-of-box" once we have both merged our work onto a same branch
* Open question is how we eventually want to control which tests are run? Currently hard-coded in the `build.sh` file https://github.com/thaliproject/Thali_CordovaPlugin/blob/story_001_vjrantal/build.sh#L61
* Did one test in CI where we had `story_001_vjrantal` and `story_001_juksilve`, but didn't yet get the results of the test run https://github.com/thaliproject/Thali_CordovaPlugin/pull/220

Above is in a PR waiting to be reviewed https://github.com/thaliproject/Thali_CordovaPlugin/pull/216.

**Comment by vjrantal** [comment]
@DrJukka: Noticed that your latest server implementation did not start performance tests on iOS locally. I had two devices connecting to a server, which printed:
```
$ jx index.js "{\"devices\":{\"ios\":\"2\",\"android\":\"2\"}}"
Star Android tests : performance tests, start tests with timer
Test[0]: testReConnect.js, timeout : 700000, data : {"timeout":"600000","rounds":"10","dataTimeout":"5000","conReTryTimeout":"2000","conReTryCount":"3"}
Star iOs tests : performance tests, start tests with timer
Test[0]: testReConnect.js, timeout : 700000, data : {"timeout":"600000","rounds":"10","dataTimeout":"5000","conReTryTimeout":"2000","conReTryCount":"3"}
listening on *:3000
got connection 
iOs  DEV607 added : 3.412 sec., device count 1
got connection 
iOs  DEV4888 added : 4.016 sec., device count 2
```
After that, nothing happens.

Expected would be that since the server was started by passing 2 and the server got 2 devices connecting, the tests would start running, but that doesn't happen.

**Comment by DrJukka** [comment]
honourcount is undefined, thus its starting with timer. if you add honourCount, then you should also set android devices to 0

**Comment by vjrantal** [comment]
The tests started to run with:
```
$ jx index.js "{\"devices\":{\"android\":\"0\",\"ios\":\"2\"},\"honorCount\":\"true\"}"
```
