### ISSUE TITLE
iOS: We should update wifiBasedNativeMock according to #1875

### ISSUE THREAD

**Issue by mlesnic** [thaliproject/Thali_CordovaPlugin#1892]
The native disconnect method on iOS devices, which is mocked in [wifiBasedNativeMock](https://github.com/thaliproject/Thali_CordovaPlugin/blob/master/test/www/jxcore/lib/wifiBasedNativeMock.js#L810) takes as arguments `peerIdentifier`and callback. After #1875 will be implemented, we should also update properly `disconnect` method in `wifiBasedNativeMock` so it will take additional parameter which is `generation`. This is also connected with #1882, where proposed call to disconnect in teardown causes whole tests to fail on Desktop.

**Comment by yaronyg** [comment]
The native disconnect which is being mocked (see [here](https://github.com/thaliproject/Thali_CordovaPlugin/blob/f2ee037319243bca1af4212343a2b3841b0d873e/thali/NextGeneration/thaliMobileNative.js#L383)) doesn't take a generation as an argument so why would we add generation as an argument to the mock?

**Comment by enricogior** [comment]
@mlesnic @yaronyg I've fixed the `disconnect` bug with [this commit](https://github.com/thaliproject/Thali_CordovaPlugin/commit/876dedb0460d3031d1a79a926aafe10b5504eee5)
So we don't have to pass the generation id in the `disconnect` call.
 
I guess the confusion was caused by this line of code:
```
Mobile('disconnect').callNative(peerIdToBeClosed, "0", function (err) 
```
That `"0"` is not the generation id, but the port number, in fact thaliMobileNativeWrapper defines a [`_disconnect`](https://github.com/thaliproject/Thali_CordovaPlugin/blob/master/thali/NextGeneration/thaliMobileNativeWrapper.js#L757-L768) method that has one input argument and a [`disconnect`](https://github.com/thaliproject/Thali_CordovaPlugin/blob/master/thali/NextGeneration/thaliMobileNativeWrapper.js#L784-L794) method that has two.

**Comment by mlesnic** [comment]
It seems I confused it with portNumber as Enrico said.

**Comment by yaronyg** [comment]
I believe the portnumber was passed in to prevent confusion. There was a potential race condition where we connect to remote peer Foo on port X. Then something goes wrong. The connection dies. So we end up connecting again to peer Foo on port Y. However it's very easy for some code (especially in the peer policy manager) who is cleaning up from the first connection to call disconnect. But now the code would be calling disconnect on the port Y connection and not the port X connection as it intended. So by specifying the port we make sure that the disconnect is for the right instance of the connection to the remote peer.

Obviously this approach isn't fool proof since it's possible for the same peer to get assigned the same port, at least in theory. A better idea would have been to have associated a UUID with each connection and to pass that in.
