### ISSUE TITLE
ThaliCore: Fatal error crash

### ISSUE THREAD

**Issue by mlesnic** [thaliproject/Thali_CordovaPlugin#1908]
Tried to run all node tests on two iOS devices and at some point it looks like `ThaliCore` crashed with error: `fatal error: unexpectedly found nil while unwrapping an Optional value`.
I will try to reproduce it.
Here are [logs](https://gist.github.com/mlesnic/7bdbf046595264d2a1675e20ce0d27c8)

![screen shot 2017-06-13 at 13 21 21](https://user-images.githubusercontent.com/19724972/27080213-38a2de18-503b-11e7-913e-7ed6f5cbea2f.png)

**Comment by enricogior** [comment]
@mlesnic if it repros, can you please type `bt` (and return) after `(lldb)`? So I can see the exact line where the crash occurred.
Anyway, I suspect I know what this problem is.

**Comment by mlesnic** [comment]
@enricogior I managed to reproduce it again today. Here is the result: 
![screen shot 2017-06-16 at 10 19 43](https://user-images.githubusercontent.com/19724972/27218191-62d361be-527d-11e7-9c9c-13a408c115c0.png)

**Comment by enricogior** [comment]
@mlesnic thanks!

**Comment by enricogior** [comment]
The log of the two crashes are slightly different, in both case the AV occurs in `VirtualSocket.closeStreams()`, but in the first case it's occurring when explicitly closing the `BrowserRelay`, in the second case it looks like an error has occurred while establishing a new connection that may still not fully initialized.
I've pushed a fix, but given the crash is hard to repro I can't say for sure that the fix is covering all the cases.
https://github.com/thaliproject/thali-ios/commit/20d724cc7727226a385b1495cbc80f8e2d97067c
