### ISSUE TITLE
Perf Test - Data transfer Rate

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#280]
We should have a perf test (ask Jukka) that measures how quickly we can move data over the "bulk" transport (Android === Bluetooth, iOS === MPCF). Make sure this runs reliably.

**Comment by yaronyg** [comment]
BTW, you have to have #272 or the iOS tests won't work at all.

**Comment by yaronyg** [comment]
11/4 - Failing on iOS even with 272. Ville needs to talk to Tobe about this. Android seems to be running fairly well locally.

**Comment by yaronyg** [comment]
11/6 - Ville is examining the code and understanding what is actually going on the wire and once that is understood then he can start to send out numbers.

**Comment by yaronyg** [comment]
11/9 - Filing bugs and found some areas where the perf calcs look wrong. Will review with Jukka tomorrow.

**Comment by yaronyg** [comment]
11/10 - We think we fixed the timing issues. We will wait for Jukka to do his check in and then we'll do a second PR with Jukka's changes.

**Comment by yaronyg** [comment]
11/13 - Now that he is back from the start up fest he will submit a PR on Monday. But not much progress on Thali today.

**Comment by vjrantal** [comment]
There is now a commit that fixes the accuracy of the data rate measure. The summary report must still be improved so that it is easy to see the data rates.

Closing this item also depends on some iOS fixes, because the data send test doesn't yet fully work on iOS. I believe @tobybrad is working with those (https://github.com/thaliproject/Thali_CordovaPlugin/issues/293 and https://github.com/thaliproject/Thali_CordovaPlugin/issues/275).

**Comment by yaronyg** [comment]
PR is out. But we can't close this yet because we can't run this on iOS yet.

**Comment by yaronyg** [comment]
iOS and Android both run in CI but in iOS we still have the crash assigned to @tobybrad

**Comment by yaronyg** [comment]
There are also some Android bugs that are blocking this as well.

**Comment by vjrantal** [comment]
Now that it was switched to use randomstring to generate the test string that is sent, the assumption that a character uses 2 bytes when encoded does not hold (it wasn't probably always accurate in the first place). Instead, one character should consume 1 byte when using UTF-8, because we only generate ASCII characters.

The assumption that UTF-8 encoding is used on Android is based on the fact that `System.getProperty("file.encoding")` returns UTF-8.

On the iOS code, I can see references to `NSUTF8StringEncoding` so based on that, UTF-8 ends up being used on iOS as well.
