### ISSUE TITLE
Fighting with WIFI in CI

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#314]

**Comment by obastemur** [comment]
@DrJukka found the solution. Define a native Java method and call it after calling toogleWifi. Make sure the call waits for toggleWifi async callback.
```
WifiManager wifiManager = (WifiManager) jxcore.activity
            .getBaseContext().getSystemService(Context.WIFI_SERVICE);
        
        if(wifiManager.reconnect()) {
          wifiManager.disconnect();
          wifiManager.reconnect();
        }
```

jxcore-cordova 0.0.8 already has this fixed. However, thali-cordova can not update to latest jxcore at the moment (quoting @yaronyg) so, we might better put this into thali-cordova project and call it from JS land.

**Comment by obastemur** [comment]
updated the code (wrong copy paste)

**Comment by yaronyg** [comment]
@DrJukka @vjrantal @tobybrad @tompaana  Please see Oguz's temporary work around for this issue. This will be fixed in JXCore when we upgrade to Cordova 0.0.8 late next week.

**Comment by DrJukka** [comment]
Will do a test run with this today (along side wifi toggling, adding this code to the callback of it)

**Comment by vjrantal** [comment]
There was some code related to this issue added at https://github.com/thaliproject/Thali_CordovaPlugin/commit/165972bae822e382b91fb3782e5cffed205c1aa8 but as far as I can tell, it isn't doing what it should be doing.

One alternative is to wait for the 0.0.8 update and then get rid of the unnecessary code that was added.

**Comment by yaronyg** [comment]
We think this is fixed by removing wi-fi direct

**Comment by vjrantal** [comment]
After the update to 0.0.8, the devices were generally able to connect to the test server at the beginning of the test, but there were lots of drop-outs during, for example, a 30 minute test. A guess was that our heavy usage of Wifi Direct might contribute to this and a test run indicated this was indeed the case.

This https://github.com/ThaliTester/TestResults/tree/51986340a77003b_CI_TEST_-_DO_NOT_MERGE_vjrantal/ was a run where usage of Wifi Direct was disabled and all devices that were able to connect in the beginning of the test were able to connect also at the end of the test.

Since we are working towards different discovery mechanism, the expectation is that this is not going to be an issue in the future so not going to "fight with Wifi" anymore at this point.
