### ISSUE TITLE
Figure out what to do with phones in CI for Android

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#427]
We need to come up with a strategy to manage Lollipop vs Marshmallow. We need to run on both and so we should be testing on both.

First, we should have at least one phone that is running KitKat just to make sure our library properly throws when running on it. We will need to teach the coordination server about the existence of this phone so it doesn't try to hand it out for tests.

Second, in an ideal world we would magically find that two of the phones that don't have the right BLE hardware to be peripherals can in fact run lollipop and Marshmallow and we would keep them around just to test that we fail properly on those phones even though they have the right OS.

Third, of the remaining phones that do have the right BLE hardware we need to split them up between Lollipop and Marshmallow. Looking at the phones list I realize we didn't get enough Nexus phones. We need them because they will run whatever is the bleeding edge. For example, my HTC Is running 6 but my Nexus phones are running 6.0.1. Oh well.

Anyway, can you please propose a plan for this mess?

**Comment by vjrantal** [comment]
> First, we should have at least one phone that is running KitKat just to make sure our library properly throws when running on it.

I wonder should we instead guard build-time that supported API level is used, i.e., set https://github.com/thaliproject/Thali_CordovaPlugin_BtLibrary/blob/8d0e7c3fd70d3f0bf350c6ed2534f28b019e7875/BtConnectorLib/btconnectorlib2/build.gradle#L12 to the appropriate value?

> we would keep them around just to test that we fail properly on those phones even though they have the right OS

Probably a small amount of code should be added so that devices send the BLE capability to the test server and test server excludes the ones that don't have proper capabilities. Not sure what the failure should look like from end user perspective though (in terms of what kind of error message in the UI and when).

> Third, of the remaining phones that do have the right BLE hardware we need to split them up between Lollipop and Marshmallow.

We could include the information about the OS in the test results next to device name so that it is easy to see from the results which device has which OS.

**Comment by yaronyg** [comment]
minSDKVersion - Yes, we should. My idea was bad.

phones with new OS but bad BLE hardware - We wouldn't have any UX. And I just realized that we actually already signed up to provide his feature. If you look at the networkChanged event it includes a blueToothLowEnergy entry and one of its values is NOT_HERE which is defined as "We depend on this radio type for this platform type but it doesn't appear to exist on this device." I added a note to #356 pointing out that we need to make sure this works right. Then it's up to the user to make sure they check this. But also note that for methods like startListeningForAdvertisements and startUpdateAdvertisingAndListening we have the 'No Native Non-TCP Support' errors which should cover this. So having devices with the right OS and the wrong hardware is still a good idea for testing.

Marking which OS each device has - Amen.

**Comment by vjrantal** [comment]
> minSDKVersion - Yes, we should. My idea was bad.

This is now done at https://github.com/thaliproject/Thali_CordovaPlugin_BtLibrary/commit/f40092288cb700e84d1cff28503352cd151d63ca.

> So having devices with the right OS and the wrong hardware is still a good idea for testing.

So, the work we are anyways when implementing the new specification covers this from functional perspective, but I think we have to think how to test this in CI. The challenge is that HW-incompatible devices should be excluded from test runs, because otherwise they ruin, for example, find peers -results (because they can't be discovered). Easy solution would be to exclude HW-incompatible devices from the test runs, but then the Thali behavior would not be tested on such devices in CI.

> Marking which OS each device has - Amen.

I created this as a separate issue https://github.com/thaliproject/Thali_CordovaPlugin/issues/443.

**Comment by yaronyg** [comment]
In terms of the right OS with the wrong hardware I assume we will have two tests, a negative test and a positive test. The negative test will only run on right OS/wrong hardware and the positive test will run on right OS/right hardware.

**Comment by vjrantal** [comment]
Current API level split in CI:
```
$ grep SDK_INT *
thali01_LGE-LG-H815.md:I/io.jxcore.node.ConnectionHelper( 9610): Build version SDK_INT: 22
thali01_samsung-SM-A500FU.md:,I/io.jxcore.node.ConnectionHelper( 6122): Build version SDK_INT: 21
thali02_LGE-LG-D722.md:I/io.jxcore.node.ConnectionHelper( 6356): Build version SDK_INT: 21
thali02_LGE-Nexus 5.md:I/io.jxcore.node.ConnectionHelper( 3269): Build version SDK_INT: 21
thali03_LGE-LG-D855.md:I/io.jxcore.node.ConnectionHelper( 6130): Build version SDK_INT: 21
thali03_motorola-XT1039.md:I/io.jxcore.node.ConnectionHelper( 4378): Build version SDK_INT: 19
thali03_samsung-SM-G800F.md:,I/io.jxcore.node.ConnectionHelper( 7157): Build version SDK_INT: 19,
thali04_motorola-XT1072.md:I/io.jxcore.node.ConnectionHelper( 6473): Build version SDK_INT: 21
thali04_samsung-SM-G900F.md:I/io.jxcore.node.ConnectionHelper( 7254): Build version SDK_INT: 21
thali04_samsung-SM-N910C.md:,I/io.jxcore.node.ConnectionHelper(11762): Build version SDK_INT: 21
thali06_HTC-HTC One M8s.md:,I/io.jxcore.node.ConnectionHelper( 6915): Build version SDK_INT: 21
thali06_LGE-LG-D802.md:I/io.jxcore.node.ConnectionHelper( 4749): Build version SDK_INT: 19
thali06_samsung-SM-A300FU.md:I/io.jxcore.node.ConnectionHelper( 6136): Build version SDK_INT: 21
thali07_samsung-SM-A500FU.md:,I/io.jxcore.node.ConnectionHelper( 6119): Build version SDK_INT: 21
thali07_samsung-SM-G900F.md:,I/io.jxcore.node.ConnectionHelper( 7465): Build version SDK_INT: 21
thali08_HTC-HTC Desire 820.md:I/io.jxcore.node.ConnectionHelper( 4528): Build version SDK_INT: 19
thali08_samsung-SM-A300FU.md:,I/io.jxcore.node.ConnectionHelper( 5713): Build version SDK_INT: 21
thali09_HTC-HTC Desire 820.md:,I/io.jxcore.node.ConnectionHelper( 4527): Build version SDK_INT: 19
thali09_LGE-Nexus 5.md:I/io.jxcore.node.ConnectionHelper( 2754): Build version SDK_INT: 19
```
@tompaana, @yaronyg: Perhaps as a short-term action, we request to take out the ones that are lower than 21? I believe some can be updated by OEM-provided firmware upgrade, but not sure about all of them.

**Comment by tompaana** [comment]
The latest version (still in the making) should handle sub-21s gracefully, but they would fails the tests. So they should be either updated or removed IMO.

**Comment by vjrantal** [comment]
> The latest version (still in the making) should handle sub-21s gracefully, but they would fails the tests. So they should be either updated or removed IMO.

Once the "is BLE advertisement supported"-function starts working again, I need to anyways implement a logic that test server knows which devices don't have the required BLE HW-capabilities. This same logic can be used to exclude devices with too low API level and thus we don't need any short-term "physical actions" to the devices in CI and can manage with code changes on our side.

I'll leave this issue open until I have implemented the logic above.

**Comment by vjrantal** [comment]
This is now solved. The app doesn't install on devices with too low API level (which is as wanted) so that case isn't tested with CI. The BLE capabilities are checked in the beginning of the unit test app and only capable devices are included in tests. So CI can safely have also non-capable devices and their behavior is reported correctly.
