### ISSUE TITLE
app crashing on ios after syncing successfully

### ISSUE THREAD

**Issue by mohlsen** [thaliproject/Thali_CordovaPlugin#445]
@vjrantal had us testing the new install code and changes from the `issue_411` branch before it gets  released.  The install, build and deploy is fine.  Seems to be more consistent than before.  p2p sync works, but after the app runs for a few minutes it crashes.  This has been repeatable on iOS 8.  We have not seen this on Android, but have not looks much yet there. 

Phone 1  crashed.  Phone 2 was the peer he was talking to.

[phone 1.txt](https://github.com/thaliproject/Thali_CordovaPlugin/files/91046/phone.1.txt)
[phone 2.txt](https://github.com/thaliproject/Thali_CordovaPlugin/files/91047/phone.2.txt)

**Comment by vjrantal** [comment]
@mohlsen: Thanks for reporting the issue!

@tobybrad: Just wanted to point out that what is tested here is essentially branch `story_001`, because the changes I made are merged to that already. Also, I think key information is testing was on iOS 8 device. FWIW, I also saw a similar-looking crash with `testSendData` performance test when I was testing on iOS 8, but have not seen it anymore on iOS 9.

**Comment by tobybrad** [comment]
Yeah.. this is a bug in the framework that appears to have been fixed in the ios 9 release. Recommend upgrading.

**Comment by yaronyg** [comment]
@mohlsen I'm going to close this for now. If we see a repro when we finally give you the new code then we can reopen.
