### ISSUE TITLE
go fix hkdf in JXcore or remove it

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#488]

**Comment by cicorias** [comment]
here's the code in question: https://github.com/jxcore/jxcore/blob/master/src/wrappers/crypto_extension.cc

**Comment by cicorias** [comment]
@yaronyg - will do a quick doc on what needs remediation.. any more tests, etc.

**Comment by yaronyg** [comment]
See the email I sent you with a bunch of issues.

**Comment by cicorias** [comment]
@yaronyg  - shouldn't this be an external / addon instead of being core to JxCore (or NodeJS)? We could still get the native speed if we follow an AddOn approach.  I've gone through nodejs add-ons and they're fairly straight-forward, especially with the 'nan' helper. Also, Async support if this is blocking the JS thread really should be there.

Also, what is the use case(s) and where in a codepath / call sequence is this happening? what are the performance targets? I ask as what makes the vNext hkdf method that @mpodwysocki had done not-performant enough to meet "some requirement"?  

Is this called 1,000/second or is this something done per session intermittently?  If it's 400/ops or 800/ops in the pure JS version, why isn't that enough?

Also, of the variables (see the benchmark code below) what is static per session, server, etc. And what truly needs to be optimized. I ask as the boringssl sync'd [here](https://github.com/cicorias/boringssl), 
you'll see that the "keys", the "ikm", "secret" are all parameters and potentially CPU consuming as well. So, just doing "derive" may not be enough. Have we a benchmark that says "derive" is 90% of something of the overall time?

```
suite.add('HKDF test', function() {
  var pubKey = crypto.createECDH('secp256k1').generateKeys();
  var expirationBuffer = crypto.randomBytes(8);
  var sxy = crypto.createECDH('secp256k1');
  sxy.generateKeys();
  sxy = sxy.computeSecret(pubKey);
  HKDF('sha256', sxy, expirationBuffer).derive('', 32);
})
```

**Comment by cicorias** [comment]
today we determined that the benefit of just doing HKDF.derive based upon the updated boringssl implementation is not enough and the hkdf.js implementation is to be used until a later point. Given the primary load is done in the steps prior (computesecret & generatekeys) we'd have to extend even further the native implementation.

At a later date will revisit, and also revisit potentially native addon vs. jxcore - core implementation.

**Comment by orangemocha** [comment]
Given that this code doesn't appear to be working too well, it hasn't been updated since the original commit, and it's no longer used by Thali, we have decided to delete it. We are essentially going to revert https://github.com/thaliproject/jxcore/commit/9cfbe48ec6a0a2cfd992fed9e33d1bcde2ede027

**Comment by enricogior** [comment]
The revert has been committed https://github.com/thaliproject/jxcore/commit/a556067002a643fd695659f49de61980ef20f005
