### ISSUE TITLE
Readme / Dev setup instructions missing details

### ISSUE THREAD

**Issue by cicorias** [thaliproject/Thali_CordovaPlugin#541]
- [ ] Detail which of Android Studio and SDK to install
- [ ] what API level is currently supported
- [ ] What JxCore -jxv level is currently supported.
- [ ] what is the right path for env vars: eg: `export ANDROID_HOME=/<installation location>/Android/sdk` doesn't exist

- [ ] Update: Ensure npm v3.x+ is NOT installed on Ubuntu

Required packages on Ubuntu:
```
sudo apt-get install lib32stdc++6
sudo apt-get install lib32z1
```

**Comment by artemjackson** [comment]
- Install latest Android Studio or `android-sdk`
  For Mac: `brew install android-sdk`
  It also sets your `ANDROID_HOME` correctly

- Current target level is `android-21`
- It's better to install latest version of jxcore (currently it is `3.1.2b`)
  For Mac it can be dowloaded from [here](https://jxcore.blob.core.windows.net/jxcore-release/jxcore/0312b/release/jx_osx64v8.zip) 

- If you have already installed `android-sdk` the correct `ANDROID_HOME` sets automaticaly
  Otherwise set `ANDROID_HOME` to `/<installation location>/android-sdk` and `PATH` to `${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools`
   E.g. on my machine it is
    ```
   export ANDROID_HOME=/usr/local/Cellar/android-sdk/24.4.1_1/
   export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
   ```
