### ISSUE TITLE
Something is seriously wrong with node-ssdp

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#678]
I'm running a test where I call update advertising and then call it again to make sure that we get a new peer id. The thing I notice though is that we keep getting advertisements from before the second call to update even though I confirmed that all the machines in the test have called update a second time. I stepped into the code and the USN does appear to be changed. So I haven't figure out yet how the heck the old addresses are still around to be advertised.

I even get advertisements for myself! In this case the situation seems to be that it was an old advertisement (e.g. we had called updateAdvertising) but since it has the same address when we 'received it' we didn't filter it out (since our USN is now a different value) and so we ended up connecting to ourselves! Where are these old advertisements coming from?!?!

**Comment by vjrantal** [comment]
Here is a basic test that shows what *should* happen https://gist.github.com/vjrantal/5caa81d55476df80f2ab#file-test-js.

When you run that, you see this output https://gist.github.com/vjrantal/5caa81d55476df80f2ab#file-output-txt.

You see that after the second update call, there is an SSDP message with the same USN https://gist.github.com/vjrantal/5caa81d55476df80f2ab#file-output-txt-L32 and this is the byebye message. This is as expected after an update call and will trigger a peer availability change with hostAddress and portNumber set to null (remember to filter these out so that you don't try to connect to unavailable peers).

At the end of the output, you see that after stop, no more SSDP messages are sent.

Another thing to note is that in the output, all SSDP messages are kind of twice and that is expected, because they are there once via the Wifi transport and once via the non-TCP transport that is mocked using Wifi in the desktop.

Could you try to edit the test.js linked to reproduce the issue you are talking about and I'll try to figure out what goes wrong. Naturally, there can be bugs in the code that only trigger in certain scenarios.

**Comment by vjrantal** [comment]
> I'm running a test where I call update advertising and then call it again to make sure that we get a new peer id.

Could you push this test perhaps to a temporary branch so that I would have some code to reproduce the issue?

> Where are these old advertisements coming from?!?!

There are always byebye advertisements from the previous USN value, but if you keep seeing alive advertisements from the old USN values, that sounds like a bug.

**Comment by vjrantal** [comment]
I found one issue that I fixed at https://github.com/thaliproject/Thali_CordovaPlugin/pull/680. @yaronyg please do a code review.

> we didn't filter it out (since our USN is now a different value) and so we ended up connecting to ourselves!

Above shouldn't have happened even with the above-mentioned issue, because it caused only peer unavailable messages to be sent from self. You should not try to connect to a peer that is unavailable so I suggest you review your code to act properly based on if the `portNumber` and `hostAddress` properties are `null`.
