### ISSUE TITLE
Google Play will not accept apps with old version of OpenSSL in JXCore

### ISSUE THREAD

**Issue by mohlsen** [thaliproject/Thali_CordovaPlugin#741]
As of July 11, Google Play store will no longer accept app's into the store that use older versions of OpenSSL.  This includes the OpenSSL 1.0.1p that is in our custom build of JXCore, v0.3.1.2.  We got this warning from Google Play at the time of our last upload.

Not sure if we will just have to fix this in our [fork of jxcore](https://github.com/thaliproject/jxcore), or if this is something that we can submit back to jxcore propper, since I think @obastemur said they might take fixes and patches.  Either way, we'll have to build and host the binary.

JXCore issue: https://github.com/jxcore/jxcore/issues/846

**Comment by mohlsen** [comment]
seems like this is a simple fix, just dropping in newer version of OpenSSL into https://github.com/jxcore/jxcore/tree/master/deps/openssl/openssl.  Will just need to work out logistics of where the fix lands, and building / hosting the binaries of the custom build.  Will need to coordinate with @yaronyg

**Comment by yaronyg** [comment]
@enricogior and Diego have figured out how to properly configure the environment so they can build for different platforms which was an issue because they already figured out how to put in the new OpenSSL but when they did a build it would only be for the platform they were running on. Now that this is fixed they hope to have a new build ready by tomorrow. The big unknown is testing on iOS and Android. They have already tested on Linux and Windows. They also need to test on Mac.

**Comment by yaronyg** [comment]
The port works on the desktop OS's but it won't even compile on Android! So they are seriously blocked there. Diego is working on this now. The real problem is that the t release of OpenSSL has 500 files that have changed so it's a big deal. Also if we have to do all this work to get to 1.0.1t then maybe we go to 1.0.2?

**Comment by yaronyg** [comment]
Making progress on Android. The plan is to stick with 1.0.1 because 1.0.2 has 1400 files changed vs 500 in 1.0.1.

**Comment by enricogior** [comment]
Compilation on Android is now working.

**Comment by yaronyg** [comment]
Next up is OS/X and then iOS

**Comment by enricogior** [comment]
Compilation on macOS and iOS is OK. Next is running tests on macOS, Android and iOS emulators.

**Comment by yaronyg** [comment]
Please provide a count of how many tests are failing and are they the same on all platforms?

**Comment by software601** [comment]
If the compiling for Android works - where can I get a copy? (software601@gmail.com)

**Comment by enricogior** [comment]
Hi @software601 
we haven't released yet, it compiles but there are bugs to fix. Hopefully it will be available next week.

**Comment by software601** [comment]
Thanks for the effort.

**Comment by yaronyg** [comment]
There are tests that are sometimes passing and sometimes not depending on what test configuration we use. We are investigating.

**Comment by yaronyg** [comment]
All the desktop tests are passing that relate to OpenSSL. Hope to run the Android tests today. The tests are dependent on having a stand alone version of JX which you can't do on iOS.

**Comment by yaronyg** [comment]
There are some OpenSSL features that have been removed in later releases of Node and we need to removed them in our code and pull the related tests.

There are some assembly files that just showed up in the new version of Node and we don't know where those files came from! They are trying to figure out where the file is from.

**Comment by enricogior** [comment]
Disable SSLv2: work done, it wasn't as simple as cherry-picking the fix from nodejs because jxcore has a different file structure and names for the file involved (code from node.cc moved to jxcore.cc,  node_crypto.cc moved to a subfolder etc.).

Asm files: they are created when building OpenSSL (you have to create them for each specific platform you want to support). We may just take all of them from nodejs and replace the old ones. We only need to generate them for a couple of different platforms to make sure that they are what we think they are ;)

**Comment by yaronyg** [comment]
Tomorrow is a vacation day for Diego and Enrico so they will be back on this on Monday. Hopefully ship on Tuesday. Just need to update the assembly files and disable the ciphers.

**Comment by yaronyg** [comment]
There was a problem running the scripts that generated the assembly files in OpenSSL but that appears fixed now. They need to verify the tests on Android since we do have some test failures there. And we are just now figuring out how to get a device for iOS that we can jailbreak so we can test there as well.

**Comment by yaronyg** [comment]
At this point all the make files, assembly files, sha256 and sha512 validation files, etc. all seem 'done'. Today they will push a PR but they still don't have an iPhone set up right to test on. And there is still some Android failing tests that need to be investigated. but these 20 tests were failing before so they aren't a regression.

**Comment by yaronyg** [comment]
There was a failure on Ubuntu 16.04 that turns out to be a difference in behavior with Ubuntu 12 which Travis uses. So this isn't a regression but we need to fix it so that the dev desktop works.

**Comment by yaronyg** [comment]
There are 59 tests that use OpenSSL. On Android 55 pass and 4 fail. But there are at least 6 that are skipped but reported as passed. Diego is going through every single file to figure out which ones are passed or skipped. He has almost finished for 59 but there are another 600 tests that on Mac OS are all 'passing' but are they passing or skipped?

Newer version of Node at least have an output log (our version doesn't) and have a CI that understands skipped. But also the Nubisa folks disabled some tests (skipped them).

We are going to split the work. When we are passing the existing Nubisa tests (which we are on Android but we don't have a jail broken iPhone yet to test there) then we will do a release. And I will create a separate bug to track the tests issue.

**Comment by yaronyg** [comment]
Diego has managed to run some of the OpenSSL tests on the iOS simulator using Jxcore-Cordova. Not sure of the details yet. But if it works we can use this in Travis!!!!

**Comment by yaronyg** [comment]
We pass on iOS! PR has been submitted!

**Comment by software601** [comment]
If the compiling for Android works now how where do I get updated jx (3.1.1) ?

**Comment by yaronyg** [comment]
We will be creating another work item to do the actual publishing. It should be available on our [distribution page](https://github.com/thaliproject/jxbuild/blob/master/distribute.md) when it's ready. But please keep in mind that these releases are NOT officially supported. You are free to use them but they don't come with any kind of support or anything else.
