### ISSUE TITLE
implement MPC's advertise functions

### ISSUE THREAD

**Issue by baydet** [thaliproject/Thali_CordovaPlugin#822]
Part of #769 

startUpdateAdvertisingAndListening
stopAdvertisingAndListening

**Comment by yaronyg** [comment]
Writing tests and should be done tomorrow.

**Comment by yaronyg** [comment]
We had the tests passing on the emulator but they don't pass on an actual device the test doesn't pass. This test is a ping back, it's a unit test that runs on a single device and there appears to be differences between how the emulator handles ping back and how the device does.

**Comment by yaronyg** [comment]
Still having problem that when running on the device things don't work the same as on the machine. The problem seems to be with our test runner, not the device. We need a separate issue for test runner. But he should just use normal xctest and not the custom runner. @larryonoff will fix the test framework.
