### ISSUE TITLE
Thali Manager is designed to be stopped anytime.

### ISSUE THREAD

**Issue by andrew-aladev** [thaliproject/Thali_CordovaPlugin#838]
There is a method to force empty replications: bump `update_seq` of Pouch DB. This is just a hack but it doesn't matter. We will obtain many requests to:

1. `/NotificationBeacons`
2. `db/_changes`
3. `db/_bulk_docs`
4. `db/_local/something`

Calls can looks like `1, 3, 1, 4, 2, 2, 1, 4, 3, 4, 3, 2`. I was just wondering what will be if we will try to stop these requests when each request has been started at least once. For example:

`1, 3, 1, 4, 2, <stop here!> 2, 1, 4, 3, 4, 3, 2`

Please checkout my branch `vNext_aaladev_507`. There is a test.

1. `cd test/www/jxcore`
2. `DEBUG=* jx runCoordinatedTests.js --filter=bv_tests/disabled/testThaliManagerStopCoordinated.js`

You will obtain something like:

```
DEBUG thaliReplicationPeerAction: Got error on replication -  500 connect ECONNREFUSED

Uncaught Promise Rejection: Error: connect ECONNREFUSED

Trace: { [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  status: 500,
  result: 
   { ok: false,
     start_time: Sun Aug 07 2016 22:06:48 GMT+0300 (MSK),
     docs_read: 0,
     docs_written: 0,
     doc_write_failures: 0,
     errors: [ [Circular] ],
     status: 'aborting',
     end_time: Sun Aug 07 2016 22:06:49 GMT+0300 (MSK),
     last_seq: 0 } }
    at process.tests (/Users/hiqouser/workspace/Thali_CordovaPlugin/test/www/jxcore/lib/thaliTape.js:38:11)
    at process.emit (events.js:85:17)
    at Array.1 (/Users/hiqouser/workspace/Thali_CordovaPlugin/test/www/jxcore/node_modules/lie/lib/index.js:128:19)
    at nextTick (/Users/hiqouser/workspace/Thali_CordovaPlugin/test/www/jxcore/node_modules/immediate/lib/index.js:61:18)
    at process._tickCallback (node.js:917:13)

Error: connect ECONNREFUSED
    at errnoException (net.js:837:11)
    at Object.afterConnect [as oncomplete] (net.js:829:19)
****TEST_LOGGER:[PROCESS_ON_EXIT_FAILED]****
```

So we've got an unhandled exception. Exception can be like 'connection refused' or 'timeout' or something like this. This is not good.

We need to investigate is there a problem in Pouch DB. Than we have to implement the proper handling of such exceptions.

**Comment by yaronyg** [comment]
Yup. Wouldn't be the first. The trick here is to manually install bluebird under test/www/jxcore/node_modules/pouchdb-node/lib/index.js and figure out where pouchdb-core is (probably in a sibling directory) and then go there to lib/index.js and you will see a pointer to pouchdb-promise (which is probably also in a sibling directory) and inside of pouchdb-promise/lib/index.js is where they set the promise for PouchDB. Switch that with Bluebird and activate long stacks (see http://bluebirdjs.com/docs/api/promise.config.html, look for longStackTraces). Once you set that up then trigger the error and you will be able to get the full stack all the way up and see exactly where the problem is coming from.

**Comment by yaronyg** [comment]
I'm not sure what the numbers above actually mean. What do the integers represent? They can't be sequence numbers because sequence numbers are monotonically increasing. 

Also why do you need to bump update_seq via sinon? Why not just add a doc? It would do the same thing but not do anything our code wasn't expecting?

I wouldn't be so quick, btw, to necessarily blame pouchDB. This test should be using a brand new DB with no docs which means its sequence number is probably 0. But we return in the spy  is sequence number 1. I'm not sure what changes and others are going to do when you pass them 1 but my guess is, nothing. They will wait until the sequence number hits 1 and do nothing until then. So I'm not sure what the test should do but hang. I'm not clear why it gets that error but we are starting off by doing something weird so we shouldn't be surprised when more weird things happen.

**Comment by andrew-aladev** [comment]
I've tried bluebird, it works fine. I've figured out that pouchdb throws an expection because it saw that we have closed the connection on its pending replication. This is very simple to reproduce:

https://github.com/thaliproject/Thali_CordovaPlugin/blob/vNext_aaladev_507/thali/NextGeneration/replication/thaliReplicationPeerAction.js
```
          .on('error', function (err) {
            logger.debug(
              'Got error on replication - ',
              'state:', self._cancelReplication.state,
              'cancelled:', self._cancelReplication.cancelled,
              Utils.serializePouchError(err)
            );
            self._complete([err]);
          })
```
`DEBUG=thaliReplicationPeerAction jx runCoordinatedTests.js --filter=bv_tests/disabled/testThaliManagerStopCoordinated.js | grep thaliReplicationPeerAction`

We will see something like:
> Got error on replication -  state: active cancelled: false 500 connect ECONNREFUSED
Got error on replication -  state: pending cancelled: false 500 connect ECONNREFUSED
Got error on replication -  state: pending cancelled: false 500 connect ECONNREFUSED

I've checked that these replications has been created and started before `thaliManager.stop()` call.

So the queue is:

1. replication acitons are created and started.
2. `thaliManager.stop()` is called.
3. connections are closed.
4. active replications doesn't like its connections closed.

This looks fine. We need to cancel replications before closing its connection.

I've found a [place](https://github.com/thaliproject/Thali_CordovaPlugin/blob/vNext_aaladev_507/thali/NextGeneration/replication/thaliPullReplicationFromNotification.js#L166):

```
  Object.getOwnPropertyNames(self._peerDictionary)
    .forEach(function (entryName) {
      self._peerDictionary[entryName].kill();
    });
```

`getOwnPropertyNames` will provide us with unused peer actions. Active peer actions are sitting in `this.__thaliPeerPoolInterface`. So `ThaliPullReplicationFromNotification` wont stop active actions. We are asking pool to kill those actions.

Thali manager is using `ThaliPeerPoolInterface` but it doesn't able to stop all active actions. So we need to add `stop` method to the `ThaliPeerPoolInterface` and update `ThaliPeerPoolDefault`. It will be good to add a comment why it is very important for inheritors to kill all running actions in `stop` method.

**Comment by andrew-aladev** [comment]
I think it will be good to add a 503 handler to the `ThaliManager`. It will be on the top of the connection filter.

For example I had a very rare issue with 5% chance to be reproduced:

`ThaliManager` is in stopped state but active replication handler is working. Active handler tries to make a request. We are trying to authorize its `pskIdentity`. We are assigning a default 'public' role to it. `Public` is not authorized to make a replication and it fails with 401.

Today I've understood that it should return '5xx' error. I think 503 (Service Unavailable) will be fine.

**Comment by yaronyg** [comment]
I think you mean add 503 to the router object that the ThaliManager creates, yes? Also the example you gave below shouldn't happen once we add the stop method. ThaliManager shouldn't shut down completely until the peerPoolManager returns from the stop API call.

In other words our goal should be not to need a 503 because we will only shut down the server once everything else confirms it is shut down too.

BTW, keep in mind that when we call stop we are shutting down all the network interfaces, that includes wifi. So once stop is called there shouldn't be anyway for a network request to reach us. If it can we have a security bug.

**Comment by andrew-aladev** [comment]
Ok, I will add an assert instead. It can be used if user has overloaded `stop` method incorrectly.

**Comment by andrew-aladev** [comment]
I was too optimistic. I couldn't provide a PR for #840. The question we discussed is fixed.

But there are much more serious problems to fix this issue. All things just not working at the same time. Someone ressurrects dead connections and dead scopes. I can't even formulate what the problem is. I will investigate it.

**Comment by andrew-aladev** [comment]
I've finally got it. I was on the right way. The problem now is that we are not properly using pouchdb.

> You can do so by calling cancel() and then waiting for the 'complete' event.

So `kill` of peer action couldn't be synchronous. `kill` can be synchronous only for the user, but not for pouchdb and not for thali manager. We should wait both for `replication.to` and local seq manager's `put` and `get`. When these things will be fully cancelled or completed we can proceed stopping other system parts.

**Comment by andrew-aladev** [comment]
Fixed
