### ISSUE TITLE
Update UnitTest_App to run the node tests multiple times

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#914]
We need to run our node tests (launched from UnitTest_App) in several different configurations.

In Android we need to run tests with WiFi Only, native only and Both modes.
In iOs we can only run (in CI anyway) in native only and both modes. Wifi Only won't work because the devices are not connected to a WiFi AP that will let them route to anything locally.

So we need to set up UnitTest_app.js to run the tests several times over (how many depends on the platform) and we need to create a global variable set by UnitTest_App to the enum to be used by thaliMobile that will then be used by all the tests. For tests that create thaliMobile they will use the global enum directly.

Tests below thaliMobile (e.g. testThaliMobileNative.js and testThaliMobileNativeWrapper.js) should check the enum and only run their tests if the enum is set to native or both modes. Otherwise those tests should just immediately exit.

Just to reinforce what this issue means, on Android we are going to run *all* the node tests 3 times and on iOS 2 times.

Now there is an obvious problem with all this. On Android we don't have a functioning native layer and on iOS we have neither a functioning native layer nor (due to the way the network in CI is configured) a functioning WiFi layer. So what do we do?

For now we do the following:

Android - When we are actually running on an Android device we need to have UnitTest_App replace Mobile with the mock. So we are going to use the WiFi based mock on Android. At least this lets us run our Node code and make sure it's functioning on an Android handset. And yes we will still run all three tests. They are still useful because the mock does test different things even though it's sitting on top of the WiFi layer.

iOS - Using https://github.com/thaliproject/CI/issues/63 we can actually run the iOS tests 3 times since we will use the wifi based mock. In the future (I'm going to file that bug now) we will have some iOS devices that are on the guest network (and so wifi won't work) and some on the open network (where wifi will work) and we'll need a switch to detect which one a particular device is and based on that we can run either 2 or 3 tests. But that is the future. For now, for this bug, all you have to do is make iOS behave just like Android. That is, we always replace the real mobile with the mock.

**Comment by artemjackson** [comment]
@yaronyg regarding to set up UnitTest_app tests to run several times with a global `NETWORK_TYPE`:
Currently in `vNext` tests run like [this](https://github.com/thaliproject/Thali_CordovaPlugin/blob/vNext/test/www/jxcore/UnitTest_app.js#L58-L60):
```
setImmediate(function () {
  require('./runTests.js');
});
```
It's possible to write something like that
```
global.NETWORK_TYPE = ThaliModile.networkTypes.WIFI;

setImmediate(function () {
  require('./runTests.js');
});
```
to run tests as if WiFi is being used. And it would be ok, but if it's desired to run tests more than once (e.g. with `WIFI` and `NATIVE` network types) it seems to be impossible to write something like that
```
networkTypes.forEach(networkType => {
  global.NETWORK_TYPE = networkType;
  setImmediate(() => {
    require('./runTests.js');
  });
});
```
Because of asynchronous run of `require('./runTests.js')` `NETWORK_TYPE` will be overwritten on the next `forEach` step while previous `runTests.js` is not finished.
And it seems that we can't make ` require('./runTests.js')` synchronous because this uses a lot of asynchronous code internally(e.g. `thaliTape`) that would not notify us about its finish.

The only one solution that I see is to run `UnitTest_app.js` with specified as argument `NETWORK_TYPE`.

Please correct me if I wrong.

**Comment by yaronyg** [comment]
Is there any reason we can't have runTests export a start method that returns a promise? Then we could call it three times with the global variable set differently for each run?

**Comment by artemjackson** [comment]
@yaronyg sounds good, but then `thaliTape.begin(...)` needs to return a `Promise` as well
