### ISSUE TITLE
Client connection timeout when server has answered

### ISSUE THREAD

**Issue by evabishchevich** [thaliproject/Thali_CordovaPlugin#959]

**Comment by yaronyg** [comment]
What we are seeing is that in some cases two of the 3 devices have completed a test and gone to tear down before the third device has completed the test and so the test can never pass because the other devices aren't available anymore. This should not be possible. There is a bug somewhere that is allowing devices to enter teardown before everybody is ready for teardown.

**Comment by yaronyg** [comment]
We see this in the logs but we haven't caught it on desktop.
