### ISSUE TITLE
Find all the coordinated tests that don't pass

### ISSUE THREAD

**Issue by evabishchevich** [thaliproject/Thali_CordovaPlugin#990]

**Comment by evabishchevich** [comment]
There are a bunch of tests that don't reliably pass:
1. 'initial peer discovery' in testThaliMobileNativeDiscoveryCoordinated. It may be connected with teardown problem is test server.
2. 'can do HTTP requests after connections are cut'
3. 'We provide notification when a listener dies and we recreate it'
4. 'Action fails because of a bad hostname.'

**Comment by yaronyg** [comment]
Based on running the tests in isolation our currently belief is that the only tests that are failing due to native issues are 2 and 5. The rest we think are having issues with reliably passing due to known problems in our test framework.

We have #991 to cover thaliMobileNativeWrapper and then we will look at 5, we don't have a bug for it yet. @evabishchevich is waiting for @andrew-aladev to fix the ping time out and then we can retry the tests all together and confirm that the failure there is not due to native issues but to our test framework.

**Comment by evabishchevich** [comment]
There is bug in Coordinated replication action test. This test tries to do work even after it's finished
